package pe.bhintranet.model.bean;

import java.util.Date;

public class Usuario {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.codUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Long codusuario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.loginName
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String loginname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.clave
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String clave;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.nombres
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String nombres;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.apellidos
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String apellidos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.sexo
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String sexo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.fechaNacimiento
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Date fechanacimiento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.dni
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String dni;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.telefono
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.celular
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String celular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.correoEmpresa
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String correoempresa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.correoPersonal
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String correopersonal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.paginaWeb
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String paginaweb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.direccion
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String direccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.resumenCv
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String resumencv;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.codFotoUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Long codfotousuario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.fechaRegistro
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.fechaAlta
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.fechaBaja
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.comentario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String comentario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.codPersona
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private Long codpersona;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.tipoUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String tipousuario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuario.estado
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    private String estado;

    private String rol;
      
     public Usuario() {
        this.rol="ASESOR";
    }
     
    public Usuario(Long codusuario, String loginname, String clave, String nombres) {
        this.codusuario = codusuario;
        this.loginname = loginname;
        this.clave = clave;
        this.nombres = nombres;
        this.rol="ASESOR";        
    }
    
        public Usuario(Long codusuario, String loginname, String clave, String nombres,String apellidos,String estado) {
        this.codusuario = codusuario;
        this.loginname = loginname;
        this.clave = clave;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.estado = estado;
        this.rol="ASESOR";        
    }

    
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.codUsuario
     *
     * @return the value of usuario.codUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Long getCodusuario() {
        return codusuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.codUsuario
     *
     * @param codusuario the value for usuario.codUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setCodusuario(Long codusuario) {
        this.codusuario = codusuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.loginName
     *
     * @return the value of usuario.loginName
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.loginName
     *
     * @param loginname the value for usuario.loginName
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.clave
     *
     * @return the value of usuario.clave
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getClave() {
        return clave;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.clave
     *
     * @param clave the value for usuario.clave
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setClave(String clave) {
        this.clave = clave == null ? null : clave.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.nombres
     *
     * @return the value of usuario.nombres
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.nombres
     *
     * @param nombres the value for usuario.nombres
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setNombres(String nombres) {
        this.nombres = nombres == null ? null : nombres.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.apellidos
     *
     * @return the value of usuario.apellidos
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getApellidos() {
        return apellidos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.apellidos
     *
     * @param apellidos the value for usuario.apellidos
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos == null ? null : apellidos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.sexo
     *
     * @return the value of usuario.sexo
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.sexo
     *
     * @param sexo the value for usuario.sexo
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setSexo(String sexo) {
        this.sexo = sexo == null ? null : sexo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.fechaNacimiento
     *
     * @return the value of usuario.fechaNacimiento
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Date getFechanacimiento() {
        return fechanacimiento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.fechaNacimiento
     *
     * @param fechanacimiento the value for usuario.fechaNacimiento
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.dni
     *
     * @return the value of usuario.dni
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.dni
     *
     * @param dni the value for usuario.dni
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setDni(String dni) {
        this.dni = dni == null ? null : dni.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.telefono
     *
     * @return the value of usuario.telefono
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.telefono
     *
     * @param telefono the value for usuario.telefono
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.celular
     *
     * @return the value of usuario.celular
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.celular
     *
     * @param celular the value for usuario.celular
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.correoEmpresa
     *
     * @return the value of usuario.correoEmpresa
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getCorreoempresa() {
        return correoempresa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.correoEmpresa
     *
     * @param correoempresa the value for usuario.correoEmpresa
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setCorreoempresa(String correoempresa) {
        this.correoempresa = correoempresa == null ? null : correoempresa.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.correoPersonal
     *
     * @return the value of usuario.correoPersonal
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getCorreopersonal() {
        return correopersonal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.correoPersonal
     *
     * @param correopersonal the value for usuario.correoPersonal
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setCorreopersonal(String correopersonal) {
        this.correopersonal = correopersonal == null ? null : correopersonal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.paginaWeb
     *
     * @return the value of usuario.paginaWeb
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getPaginaweb() {
        return paginaweb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.paginaWeb
     *
     * @param paginaweb the value for usuario.paginaWeb
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setPaginaweb(String paginaweb) {
        this.paginaweb = paginaweb == null ? null : paginaweb.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.direccion
     *
     * @return the value of usuario.direccion
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.direccion
     *
     * @param direccion the value for usuario.direccion
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.resumenCv
     *
     * @return the value of usuario.resumenCv
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getResumencv() {
        return resumencv;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.resumenCv
     *
     * @param resumencv the value for usuario.resumenCv
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setResumencv(String resumencv) {
        this.resumencv = resumencv == null ? null : resumencv.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.codFotoUsuario
     *
     * @return the value of usuario.codFotoUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Long getCodfotousuario() {
        return codfotousuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.codFotoUsuario
     *
     * @param codfotousuario the value for usuario.codFotoUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setCodfotousuario(Long codfotousuario) {
        this.codfotousuario = codfotousuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.fechaRegistro
     *
     * @return the value of usuario.fechaRegistro
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.fechaRegistro
     *
     * @param fecharegistro the value for usuario.fechaRegistro
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.fechaAlta
     *
     * @return the value of usuario.fechaAlta
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.fechaAlta
     *
     * @param fechaalta the value for usuario.fechaAlta
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.fechaBaja
     *
     * @return the value of usuario.fechaBaja
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.fechaBaja
     *
     * @param fechabaja the value for usuario.fechaBaja
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.comentario
     *
     * @return the value of usuario.comentario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.comentario
     *
     * @param comentario the value for usuario.comentario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setComentario(String comentario) {
        this.comentario = comentario == null ? null : comentario.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.codPersona
     *
     * @return the value of usuario.codPersona
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public Long getCodpersona() {
        return codpersona;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.codPersona
     *
     * @param codpersona the value for usuario.codPersona
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setCodpersona(Long codpersona) {
        this.codpersona = codpersona;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.tipoUsuario
     *
     * @return the value of usuario.tipoUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getTipousuario() {
        return tipousuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.tipoUsuario
     *
     * @param tipousuario the value for usuario.tipoUsuario
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario == null ? null : tipousuario.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuario.estado
     *
     * @return the value of usuario.estado
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuario.estado
     *
     * @param estado the value for usuario.estado
     *
     * @ibatorgenerated Thu Dec 07 02:59:13 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
    
    public String getRol() {
        return rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }  
}